# Generated by Django 2.1.4 on 2019-01-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('nni', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('telephone', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('nlocation', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('date_location', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Marques',
            fields=[
                ('model', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.IntegerField(max_length=3)),
                ('coutparjour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marque', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Penalisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raison', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RetourVoiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retour', models.DateTimeField()),
                ('nlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voitures.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Voitures',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('0', 'disponible'), ('1', 'indisponible')], max_length=1)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voitures.Marques')),
            ],
        ),
        migrations.AddField(
            model_name='penalisation',
            name='nlocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voitures.RetourVoiture'),
        ),
        migrations.AddField(
            model_name='locations',
            name='matricule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voitures.Voitures'),
        ),
        migrations.AddField(
            model_name='locations',
            name='nni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voitures.Clients'),
        ),
    ]
