# Generated by Django 2.1.4 on 2019-01-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0002_auto_20190104_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marques',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='clients',
            name='nni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='telephone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='montant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='nlocation',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marques',
            name='coutparjour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penalisation',
            name='cout',
            field=models.IntegerField(),
        ),
    ]
