# Generated by Django 2.1.4 on 2019-01-06 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0003_auto_20190104_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='voitures',
            name='date_ajout',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
