# Generated by Django 2.1.4 on 2019-01-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0004_voitures_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='nlocation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
